'use strict';
let state, csrf, current, busy=false;
const q=id=>document.getElementById(id); const el=(t,x,c)=>{const n=document.createElement(t);if(x!==undefined)n.textContent=x;if(c)n.className=c;return n;};
async function api(path, body) { const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json','X-Reconciliation-Token':csrf},body:JSON.stringify(body)}:{}); const x=await r.json();if(!r.ok)throw Error(x.error||'Request failed');return x; }
async function choose(id,decision){if(busy)return;busy=true;render();try{state=await api('/api/decision',{expectedRevision:state.revision,judgmentItemID:id,decision});q('error').textContent='';}catch(e){q('error').textContent=e.message+'. Reload to recover the last saved state.';}finally{busy=false;render();}}
async function open(id){try{current=await api('/api/item/'+encodeURIComponent(id));render();}catch(e){q('error').textContent=e.message;}}
function source(parent, value, title){const d=el('details'),s=el('summary',title);d.append(s,el('div',value.text,'source'));parent.append(d);}
function render(){if(!state)return;q('progress').textContent=`${state.answered} / ${state.total} final decisions saved locally`;const nav=q('items');nav.replaceChildren();Object.keys(state.decisions).length;const ids=Object.keys(current?{}:{}); const ordered=window.itemIDs||[];ordered.forEach((id,i)=>{const b=el('button',`${i+1}. ${id} ${state.decisions[id]?'✓':'○'}`);b.disabled=busy;b.onclick=()=>open(id);if(current&&current.judgmentItem.judgmentItemID===id)b.className='current';nav.append(b);});const root=q('review');root.replaceChildren();if(!current)return;const item=current.judgmentItem,a=item.assertion;root.append(el('h2',item.judgmentItemID+' · '+item.recordKind),el('h3',item.operationalTarget.name));if(item.reviewGuidance){root.append(el('p','Positive criterion: '+item.reviewGuidance.positiveCriterion,'guidance'),el('p','Boundary: '+item.reviewGuidance.boundary,'guidance'));}if(item.recordKind==='node'){root.append(el('p',a.label),el('p','Identity action: '+a.action));a.attributes.forEach(x=>root.append(el('p',x.attributeName+': '+String(x.value))));}else{root.append(el('p',(a.sourceEndpoint.displayLabel||a.sourceEndpoint.label)+' → '+a.relationName+' → '+(a.targetEndpoint.displayLabel||a.targetEndpoint.label)),el('p','Scope: '+a.relationScope));}root.append(el('h3','Blinded initial judgments'),el('p','Initial review A: '+current.blindedInitialJudgments.initialReviewA.replaceAll('_',' ')),el('p','Initial review B: '+current.blindedInitialJudgments.initialReviewB.replaceAll('_',' ')));source(root,current.primarySource,'Complete authorized primary source text');current.authorizedContext.forEach(x=>source(root,x,'Additional authorized context: '+x.sectionTitle));root.append(el('h3','Cited evidence'));item.paragraphContexts.forEach(c=>{root.append(el('small',c.renderingLabel+' · '+c.sourceUnitID));const p=el('div',undefined,'paragraph');c.segments.forEach(s=>p.append(el('span',s.text,s.highlights.join(' '))));root.append(p);});const field=el('fieldset');field.append(el('legend','Final reconciliation status'));state.allowedFinalDecisions.forEach(v=>{const label=el('label'),input=document.createElement('input');input.type='radio';input.name='decision';input.checked=state.decisions[item.judgmentItemID]===v;input.disabled=busy;input.onchange=()=>choose(item.judgmentItemID,v);label.append(input,document.createTextNode(' '+v.replaceAll('_',' ')));field.append(label);});root.append(field);}
async function start(){try{state=await api('/api/state');csrf=state.csrfToken;const p=await fetch('/api/package');if(!p.ok)throw Error('Package index unavailable');window.itemIDs=await p.json();await open(window.itemIDs.find(x=>!state.decisions[x])||window.itemIDs[0]);}catch(e){q('error').textContent=e.message;}}start();
